package com.example.models;

import java.time.LocalDateTime;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;


    @Entity
    @Table(name="messages")
    public class ChatMessage {
        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        private Long id;
        private String sender;
        private String receiver;
        private String groupName;
        private String content;

        private LocalDateTime timeStamp;
        
    // Constructor for group chat
    public ChatMessage(String sender, String groupName, String content, LocalDateTime timeStamp) {
        this.sender = sender;
        this.groupName = groupName;
        this.content = content;
        this.timeStamp = timeStamp;
    }

    // Constructor without id (for when the id will be generated by the database)
    public ChatMessage(String sender, String content, LocalDateTime timeStamp) {
        this.sender = sender;
        this.content = content;
        this.timeStamp = timeStamp;
    }

        public ChatMessage() {
        }

        // Getters and Setters
        public String getSender() {
            return sender;
        }
    
        public void setSender(String sender) {
            this.sender = sender;
        }
    
        public String getContent() {
            return content;
        }
    
        public void setContent(String content) {
            this.content = content;
        }

        public Long getId() {
            return id;
        }

        public void setId(Long id) {
            this.id = id;
        }

    public LocalDateTime getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(LocalDateTime timeStamp) {
        this.timeStamp = timeStamp;
    }

    public String getReceiver() {
        return receiver;
    }

    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    @Override
    public String toString() {
        return "ChatMessage [id=" + id + ", sender=" + sender + ", receiver=" + receiver + ", groupName=" + groupName
                + ", content=" + content + ", timeStamp=" + timeStamp + "]";
    }
}

